import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppmori = localFont({
  variable: "--font-ppmori",
  src: [
    { path: "../public/fonts/PPMori-Extralight.otf", weight: "200", style: "normal" },
    { path: "../public/fonts/PPMori-ExtralightItalic.otf", weight: "200", style: "italic" },
    { path: "../public/fonts/PPMori-Regular.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/PPMori-Italic.otf", weight: "400", style: "italic" },
    { path: "../public/fonts/PPMori-Semibold.otf", weight: "600", style: "normal" },
    { path: "../public/fonts/PPMori-SemiboldItalic.otf", weight: "600", style: "italic" },
    { path: "../public/fonts/PPMori-Black.otf", weight: "900", style: "normal" },
    { path: "../public/fonts/PPMori-BlackItalic.otf", weight: "900", style: "italic" },
  ],
});

const instrument = localFont({
  variable: "--font-instrument",
  src: [
    { path: "../public/fonts/InstrumentSerif-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/InstrumentSerif-Italic.ttf", weight: "400", style: "italic" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppmori.variable} ${instrument.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
